import { DatabaseManager } from "../db/manager";
import { loadConfig } from "../config";
import type { ColumnDefinition } from "@boltstore/utils";
import { error as cliError, out, info, success } from "../cli-style";

const TS_TYPE_MAP: Record<string, string> = {
  TEXT: "string",
  INTEGER: "number",
  REAL: "number",
  BOOLEAN: "boolean",
  BLOB: "string",
  DATETIME: "string",
};

function columnToType(col: ColumnDefinition): string {
  return TS_TYPE_MAP[col.type] || "unknown";
}

function columnToTS(col: ColumnDefinition): string {
  const tsType = columnToType(col);
  const opt = col.required ? "" : "?";
  return `  ${col.name}${opt}: ${tsType};`;
}

function sanitizeInterfaceName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^(\d)/, "_$1");
}

const IRREGULAR_PLURALS = new Set(["status", "bus", "campus", "focus", "cactus", "gas", "species", "series"]);

function singularize(name: string): string {
  if (IRREGULAR_PLURALS.has(name)) return name;
  if (name.endsWith("ies")) return name.slice(0, -3) + "y";
  if (name.endsWith("ses") || name.endsWith("xes") || name.endsWith("ches") || name.endsWith("shes")) return name.slice(0, -2);
  if (name.endsWith("s") && !name.endsWith("ss") && name.length > 4) return name.slice(0, -1);
  return name;
}

function generateInterfaces(
  collections: Array<{ name: string; columns: ColumnDefinition[]; relations?: Record<string, import("@boltstore/utils").CollectionRelation> }>,
): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by boltstore types");
  lines.push("// Re-run `boltstore types --db <id>` to update\n");
  lines.push("import type { BoltstoreRecord } from \"@boltstore/client\";\n");

  for (const col of collections) {
    const name = sanitizeInterfaceName(col.name);
    const singular = singularize(name);

    // Main interface (without system columns)
    const userCols = col.columns.filter(
      (c) => c.name !== "id" && c.name !== "created_at" && c.name !== "updated_at",
    );
    const generatedCols = userCols.filter((c) => c.generated);
    const regularCols = userCols.filter((c) => !c.generated);

    if (regularCols.length === 0 && generatedCols.length === 0) continue;

    lines.push(`export interface ${singular} {`);
    for (const c of regularCols) {
      lines.push(columnToTS(c));
      if (c.default !== undefined) {
        lines.push(`  /** @default ${JSON.stringify(c.default)} */`);
      }
    }
    for (const c of generatedCols) {
      lines.push(`  /** Generated: ${c.generated!.expression}${c.generated!.stored ? " [STORED]" : " [VIRTUAL]"} */`);
      lines.push(columnToTS(c));
    }

    // Relation types
    if (col.relations) {
      for (const [relName, rel] of Object.entries(col.relations)) {
        const relType = sanitizeInterfaceName(rel.foreignCollection).replace(/s$/, "");
        if (rel.type === "manyToMany" || rel.type === "hasMany") {
          lines.push(`  ${relName}?: ${relType}[];`);
        } else {
          lines.push(`  ${relName}?: ${relType} | null;`);
        }
      }
    }

    lines.push("}");
    lines.push("");

    // Typed record = fields + system columns
    lines.push(`export type ${name}Record = ${singular} & BoltstoreRecord;\n`);
  }

  return lines.join("\n");
}

export async function typesCommand(args: string[]): Promise<void> {
  const config = await loadConfig();
  const dbId = args.includes("--db") ? args[args.indexOf("--db") + 1] : undefined;
  if (!dbId) {
    cliError("Usage: boltstore types --db <database-id> [--output <file>]");
    return;
  }

  const outputFile = args.includes("--output") ? args[args.indexOf("--output") + 1] : undefined;

  const manager = new DatabaseManager({ dataDir: config.databasePath });

  if (!manager.exists(dbId)) {
    cliError(`Database "${dbId}" not found.`);
    return;
  }

  const pool = manager.get(dbId);
  const db = pool.read();

  // Read collection metadata
  const metaExists = db.query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='_collections'").get();
  if (!metaExists) {
    cliError('No collections found. The "_collections" metadata table does not exist.');
    return;
  }

  const rows = db.query(
    "SELECT name, schema_json, relations_json FROM _collections ORDER BY name",
  ).all() as Array<{ name: string; schema_json?: string; relations_json?: string }>;

  if (rows.length === 0) {
    info("No collections found.");
    return;
  }

  const collections: Array<{
    name: string;
    columns: ColumnDefinition[];
    relations?: Record<string, import("@boltstore/utils").CollectionRelation>;
  }> = [];

  for (const row of rows) {
    let columns: ColumnDefinition[] = [];
    try {
      columns = JSON.parse(row.schema_json || "[]") as ColumnDefinition[];
    } catch {
      continue;
    }

    let relations: Record<string, import("@boltstore/utils").CollectionRelation> | undefined;
    if (row.relations_json) {
      try {
        relations = JSON.parse(row.relations_json);
      } catch {
        // ignore invalid JSON
      }
    }

    collections.push({ name: row.name, columns, relations });
  }

  const output = generateInterfaces(collections);

  if (outputFile) {
    try {
      await Bun.write(outputFile, output);
      success(`Types written to ${outputFile}`);
    } catch (err: unknown) {
      cliError(`Failed to write to ${outputFile}: ${(err as Error).message}`);
    }
  } else {
    out(output);
  }
}
